name: CI
on: [push, pull_request]
defaults:
  run:
    shell: bash

concurrency:
  group: CI-${{ github.ref }}
  # Queue on all branches and tags, but only cancel overlapping PR burns.
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' || !startsWith(github.ref, 'refs/tags/') }}
jobs:
  org-check:
    name: Check GitHub Organization
    if: github.repository_owner == 'a-scie'
    runs-on: ubuntu-20.04
    steps:
      - name: Noop
        run: "true"
  ci:
    name: Tools Checks
    needs: org-check
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Check Tools
        uses: pantsbuild/actions/run-tox@v1
        with:
          tox-env: fmt-check,check
